export type { Database, Json } from './database';

import type { Database } from './database';

export type OperatorRow = Database['public']['Tables']['operators']['Row'];
export type ProfileRow = Database['public']['Tables']['profiles']['Row'];
export type MachineRow = Database['public']['Tables']['machines']['Row'];
export type ProductRow = Database['public']['Tables']['products']['Row'];
export type ProductCategoryRow = Database['public']['Tables']['product_categories']['Row'];
export type MachineProductPriceRow = Database['public']['Tables']['machine_product_prices']['Row'];
export type ParLevelRow = Database['public']['Tables']['par_levels']['Row'];
export type RFIDItemRow = Database['public']['Tables']['rfid_items']['Row'];
export type DiscountRow = Database['public']['Tables']['discounts']['Row'];
export type ExpirationRuleRow = Database['public']['Tables']['expiration_rules']['Row'];
export type DailyRollupRow = Database['public']['Tables']['daily_rollups']['Row'];
export type CogsSettingRow = Database['public']['Tables']['cogs_settings']['Row'];
export type ConsumerProfileRow = Database['public']['Tables']['consumer_profiles']['Row'];
export type CreditLedgerRow = Database['public']['Tables']['credit_ledger']['Row'];
export type ConsumerFeedbackRow = Database['public']['Tables']['consumer_feedback']['Row'];
export type AutomationRuleRow = Database['public']['Tables']['automation_rules']['Row'];
export type BonusAwardRow = Database['public']['Tables']['bonus_awards']['Row'];
export type NotificationSendRow = Database['public']['Tables']['notification_sends']['Row'];
export type ApiKeyRow = Database['public']['Tables']['api_keys']['Row'];
export type WebhookSubscriptionRow = Database['public']['Tables']['webhook_subscriptions']['Row'];
export type WebhookDeliveryRow = Database['public']['Tables']['webhook_deliveries']['Row'];
export type TagOrderRow = Database['public']['Tables']['tag_orders']['Row'];
export type TransactionRow = Database['public']['Tables']['transactions']['Row'];
export type PayoutRow = Database['public']['Tables']['payouts']['Row'];
export type PayoutTransactionRow = Database['public']['Tables']['payout_transactions']['Row'];
export type TemperatureReadingRow = Database['public']['Tables']['temperature_readings']['Row'];
export type PushSubscriptionRow = Database['public']['Tables']['push_subscriptions']['Row'];
export type MachineCommandRow = Database['public']['Tables']['machine_commands']['Row'];
export type MachineAlertPreferenceRow = Database['public']['Tables']['machine_alert_preferences']['Row'];
export type MachineAlertConditionRow = Database['public']['Tables']['machine_alert_conditions']['Row'];
export type AlertRow = Database['public']['Tables']['alerts']['Row'];
export type AuditLogRow = Database['public']['Tables']['audit_log']['Row'];
